add a parameter to allow a specific group to access compute nodes without having jobs on the node
ComputeCanada/puppet-magic_castle pull request #350
Opened 2024-04-12 18:53 UTC by mboisson

2024-05-14 21:22 UTC, cmd-ntrf requested changes

2024-05-14 21:22 UTC, cmd-ntrf commented on site/profile/manifests/slurm.pp
> +  String  $pam_access_group = undef,
If we make this an array instead, we can get rid of the if/else:
```
Array[String] $pam_acccess_groups = ['wheel']
```

2024-05-14 21:22 UTC, cmd-ntrf commented on site/profile/manifests/slurm.pp
> +  $access_conf = "
```puppet
$access_conf = @(END)
# Allow root cronjob
+ : root : cron crond :0 tty1 tty2 tty3 tty4 tty5 tty6
# Allow other groups if any
<% for $pam_access_groups.each | $group | { %->
+:<%= $group %>:ALL
<% } -%>
-:ALL:ALL
END
```

2024-05-14 21:22 UTC, cmd-ntrf commented on site/profile/manifests/slurm.pp
> +${access_conf_addon}
Then access.conf becomes
```puppet
  file { '/etc/security/access.conf':
    ensure  => present,
    content => inline_template($access_conf, { 'pam_access_groups' => $pam_access_groups }),
  }
```

2025-01-20 17:02 UTC, mboisson commented
@cmd-ntrf I have now implemented the logic the way you suggested in this PR

2025-01-24 19:29 UTC, cmd-ntrf approved these changes

2025-01-24 20:38 UTC, merged